apiVersion: apps/v1
kind: Deployment
metadata:
  name: b9-backend-app
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: b9-backend-app
  template:
    metadata:
      labels:
        app: b9-backend-app
    spec:
      containers:
      - name: b9-backend-app
        image: payalkalbhor2401/project1-backend2
        ports:
        - containerPort: 8080
