apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1-backend
  template:
    metadata:
      labels:
        app: project1-backend
    spec:
      containers:
      - name: project1-backend
        image: payalkalbhor2401/project1-backend:latest
        ports:
        - containerPort: 8080
